### ISSUE TITLE
Struggle with use case

### ISSUE THREAD

**Issue by pySilver** [marcoroth/turbo-morph#4]
Hey!

Thanks for the lib. I'm reading https://docs.stimulusreflex.com/rtfm/morph-modes to get better understanding of a real world benefits that morphdom brings comparing to typical `Turbo.StreamActions` (replace/update). Shame on me but I cannot find a good example where morphdom is better than typical stream update/replace action. 

Would you be so kind to provide more info on this?

**Comment by marcoroth** [comment]
Hey @pySilver, thanks for reaching out and bringing that up.

Yeah, there are some "edge-cases" where morph operations could come in handy, where a regular update/replace operation could cause some issues.

The most common one is loosing state which is stored on DOM elements or the reinitialization of Stimulus controllers if the root element or any children has controllers attached.

But that also depends how you write your Stimulus controllers. For some you actually want to trigger a reinitialization, for exmaple if your controller is responsible for initializing tooltips within the newly morphed HTML content. 

But if your controller is responsible for handling audio/video you don't want that controller to be reinitialized because you would loose that state and cause the media to stop.

It might be worth to convert that Twitter thread into a proper blog post for better visibility!

Thanks!
